### ISSUE TITLE
Fail to build with nodejs 12.x on Arch Linux

### ISSUE THREAD

**Issue by benkaiser** [nikhilm/node-taglib#58]
Below is the output for the issue:

```
$ taglib-config --version
1.9.1
$ node --version         
v0.12.0
$ npm install            
npm WARN engine taglib@0.8.1: wanted: {"node":">=0.10.0 <0.11"} (current: {"node":"0.12.0","npm":"2.5.1"})
\
> taglib@0.8.1 install /home/benkaiser/GIT/node-music-player/node_modules/taglib
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
make: Entering directory '/home/benkaiser/GIT/node-music-player/node_modules/taglib/build'
  CXX(target) Release/obj.target/taglib/src/bufferstream.o
In file included from ../src/bufferstream.cc:5:0:
../src/taglib.h:26:47: error: ‘Arguments’ in namespace ‘v8’ does not name a type
 v8::Handle<v8::Value> AsyncReadFile(const v8::Arguments &args);
                                               ^
../src/taglib.h:46:46: error: ‘Arguments’ in namespace ‘v8’ does not name a type
 v8::Handle<v8::Value> AddResolvers(const v8::Arguments &args);
                                              ^
taglib.target.mk:87: recipe for target 'Release/obj.target/taglib/src/bufferstream.o' failed
make: *** [Release/obj.target/taglib/src/bufferstream.o] Error 1
make: Leaving directory '/home/benkaiser/GIT/node-music-player/node_modules/taglib/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Linux 3.17.1-1-ARCH
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/benkaiser/GIT/node-music-player/node_modules/taglib
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Linux 3.17.1-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! taglib@0.8.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the taglib@0.8.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the taglib package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls taglib
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/benkaiser/GIT/node-music-player/npm-debug.log
```

This may help with fixing the issue: https://github.com/mochajs/mocha/pull/1287/files

**Comment by masterkain** [comment]
I have the same issue on OSX.

**Comment by benkaiser** [comment]
Build fine with node version 11.x. This is specifically related to node version 12.x.

**Comment by egasimus** [comment]
Same here. Anyone with them bindin'-writin' chops wanna look into fixin' this?

**Comment by egasimus** [comment]
@benkaiser I doubt it's the `childFds` thing that's causing the issue. [This](https://github.com/rvagg/nan) might be more relevant though.

**Comment by benkaiser** [comment]
I'm not really concerned with this anymore, I switched out taglib for https://github.com/leetreveil/musicmetadata over the weekend so now I have no dependencies on taglib. The only downside is slower scanning, but the upside is that its entirely JavaScript module so it doesn't depend on system libs like taglib does (making installation and cross-platform support easier)

**Comment by okonet** [comment]
Same issue on OS X with both Node 0.11.x and 5.x

**Comment by mborn319** [comment]
I get the same issue on Ubuntu 16.04 with Node 4.2.6.

**Comment by coffeegrinder** [comment]
Trying to install this but keep getting errors. Sounds good there was the alternative "musicmetadata", is there any alternative for mp4 files ?
(Linux Mint 19.2)
