### ISSUE TITLE
Installation failing on node v5.7.1 / Ubuntu 14.04

### ISSUE THREAD

**Issue by avaly** [nikhilm/node-taglib#62]
Trying to install the latest repository code on Ubuntu 14.04 with node.js v5.7.1 and `libtag1-dev` 1.2.1, I get the following failure:

```
npm i .
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.

> taglib@0.8.1 install /home/htpc/tmp/node-taglib
> node-gyp rebuild

make: Entering directory `/home/foo/tmp/node-taglib/build'
  CXX(target) Release/obj.target/taglib/src/bufferstream.o
In file included from ../src/bufferstream.cc:5:0:
../src/taglib.h:26:43: error: ‘Arguments’ in namespace ‘v8’ does not name a type
 v8::Handle<v8::Value> AsyncReadFile(const v8::Arguments &args);
                                           ^
../src/taglib.h:26:58: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
 v8::Handle<v8::Value> AsyncReadFile(const v8::Arguments &args);
                                                          ^
../src/taglib.h:46:42: error: ‘Arguments’ in namespace ‘v8’ does not name a type
 v8::Handle<v8::Value> AddResolvers(const v8::Arguments &args);
                                          ^
../src/taglib.h:46:57: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
 v8::Handle<v8::Value> AddResolvers(const v8::Arguments &args);
                                                         ^
make: *** [Release/obj.target/taglib/src/bufferstream.o] Error 1
make: Leaving directory `/home/foo/tmp/node-taglib/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.13.0-67-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/foo/tmp/node-taglib
gyp ERR! node -v v5.7.1
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
```

**Comment by nikhilm** [comment]
It is possible that a v8 upgrade broke things. I can't commit to a solid
timeline for fixing this. Happy to accept PRs though.

**Comment by Vortex375** [comment]
I created a fork and rewrote the bindings using [nan](https://github.com/nodejs/nan). Though it might not be 100% perfect yet, I can compile it on node v4.x and 5.x

Check out the "v8-compat" branch in my [fork](https://github.com/Vortex375/node-taglib/tree/v8-compat).

**Comment by nikhilm** [comment]
Thanks, could you submit a PR. That makes it easier to review.

**Comment by Vortex375** [comment]
I did. Look here: https://github.com/nikhilm/node-taglib/pull/63
